// flow-typed signature: 2ffb964174d83049fab190c38525ea8d
// flow-typed version: <<STUB>>/eslint-plugin-polymath_vgithub:PolymathNetwork/eslint-plugin-polymath/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-polymath'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-polymath' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-polymath/config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-polymath/config.js' {
  declare module.exports: $Exports<'eslint-plugin-polymath/config'>;
}
declare module 'eslint-plugin-polymath/index' {
  declare module.exports: $Exports<'eslint-plugin-polymath'>;
}
declare module 'eslint-plugin-polymath/index.js' {
  declare module.exports: $Exports<'eslint-plugin-polymath'>;
}
