// flow-typed signature: c5c63541977e094361c5bce666743eb4
// flow-typed version: <<STUB>>/polymath-core_v2_v0.1.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymath-core_v2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymath-core_v2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymath-core_v2/migrations/2_deploy_contracts' {
  declare module.exports: any;
}

declare module 'polymath-core_v2/test/TestSTExample' {
  declare module.exports: any;
}

declare module 'polymath-core_v2/test/transferManager' {
  declare module.exports: any;
}

declare module 'polymath-core_v2/truffle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymath-core_v2/migrations/2_deploy_contracts.js' {
  declare module.exports: $Exports<'polymath-core_v2/migrations/2_deploy_contracts'>;
}
declare module 'polymath-core_v2/test/TestSTExample.js' {
  declare module.exports: $Exports<'polymath-core_v2/test/TestSTExample'>;
}
declare module 'polymath-core_v2/test/transferManager.js' {
  declare module.exports: $Exports<'polymath-core_v2/test/transferManager'>;
}
declare module 'polymath-core_v2/truffle.js' {
  declare module.exports: $Exports<'polymath-core_v2/truffle'>;
}
