// flow-typed signature: 576ce9880b09a180fefbfe24b7c7caf5
// flow-typed version: <<STUB>>/web3-core-method_vbshevchenko/web3-core-method#master/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-core-method'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-core-method' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-core-method/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-core-method/src/index.js' {
  declare module.exports: $Exports<'web3-core-method/src/index'>;
}
